services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: test_password
      PGDATA: /data/postgres
      POSTGRES_DB: bank
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  furventure-bot-core:
    image: furventure-bot-core
    container_name: furventure-bot-core
    environment:
      - ConnectionString
      - FurventureBotType=Telegram Dev
    networks:
      - db
    restart: unless-stopped 
  furventure-server:
    image: "furventure-server"
    container_name: furventure-server
    environment:
      - ASPNETCORE_URLS="http://0.0.0.0:5000"
      - VIRTUAL_HOST=api.furventure.taldrin.co.uk
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.furventure.taldrin.co.uk
      - LETSENCRYPT_EMAIL=interfurcreations@gmail.com
      - ConnectionString
      - FurventureBotType=PublicSiteAlpha
    expose:
      - "5000"
    networks:
      - db
      - default
    restart: unless-stopped
  furventure-site-public:
    image: "furventure-publicsite"
    environment:
      VIRTUAL_HOST: furventure.taldrin.co.uk
      VIRTUAL_PORT: 5007
      LETSENCRYPT_HOST: furventure.taldrin.co.uk
      LETSENCRYPT_EMAIL: interfurcreations@gmail.com
      ASPNETCORE_URLS: "https://furventure.taldrin.co.uk/"
    expose:
      - "5007"
    networks:
      - db
      - default
    restart: always 
networks:
  db:
    driver: bridge
  default:
    name: nginx-proxy
    external: true

volumes:
  db: