name: AdminSiteDeploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103
      
    - name: Install dependencies
      run: dotnet restore AdminSite/InterfurCreations.AdminSite/InterfurCreations.AdminSite.csproj
      working-directory: ./AdminSite
    - name: Build
      run: dotnet publish AdminSite/InterfurCreations.AdminSite/InterfurCreations.AdminSite.csproj --configuration Release --no-restore
      working-directory: ./AdminSite
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: sftpuser
        server: 18.133.6.112
        port: 22
        ssh_private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
        local_path: AdminSite/AdminSite/InterfurCreations.AdminSite/bin/Release/net5.0/publish/*
        remote_path: /home/sftpuser/adminsite
    - name: SSH Reload system service
      uses: fifsky/ssh-action@v0.0.4
      with:
        command: |
                 cp -R /home/sftpuser/adminsite/* /var/www/admin_site/
                 sudo systemctl restart kestrel-admin-site.service
                 sudo systemctl restart nginx
        host: 18.133.6.112
        user: admin
        port: 22
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
