name: DiscordAlphaDeploy

on:
  push:
    branches: [ alpha ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103
      
    - name: Install dependencies
      run: dotnet restore InterfurCreations.AdventureGames.WorkerService
      working-directory: ./AdventureGameCore
    - name: Build
      run: dotnet build InterfurCreations.AdventureGames.WorkerService --configuration DiscordAlpha --no-restore
      working-directory: ./AdventureGameCore
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: sftpuser
        server: 18.133.6.112
        port: 22
        ssh_private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
        local_path: AdventureGameCore/InterfurCreations.AdventureGames.WorkerService/bin/DiscordAlpha/net5.0/*
        remote_path: /home/sftpuser/discordalpha
    - name: SSH Reload system service
      uses: fifsky/ssh-action@v0.0.4
      with:
        command: | 
                 sudo systemctl daemon-reload
                 sudo systemctl restart discordalpha.service
        host: 18.133.6.112
        user: admin
        port: 22
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
