name: PublicSiteDeploy

on:
  push:
    branches: 
        - '*'
        - '!master'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      
    - name: Install dependencies
      run: dotnet restore PublicSite/Server/PublicSite.Server.csproj
      working-directory: ./PublicSite
    - name: Build
      run: dotnet publish PublicSite/Server/PublicSite.Server.csproj --configuration Release --no-restore
      working-directory: ./PublicSite
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: sftpuser
        server: 18.133.6.112
        port: 22
        ssh_private_key: ${{ secrets.SERVER_PRIVATE_KEY }}
        local_path: PublicSite/PublicSite/Server/bin/Release/netcoreapp3.1/publish/*
        remote_path: /home/sftpuser/publicsite
    - name: SSH Reload system service
      uses: fifsky/ssh-action@v0.0.4
      with:
        command: |
                 mv /home/sftp/user/publicsite/* /var/www/furventure_public/
                 sudo systemctl restart kestrel-furventure-public.service
                 sudo systemctl restart nginx
        host: 18.133.6.112
        user: admin
        port: 22
        key: ${{ secrets.SERVER_PRIVATE_KEY }}
